rockorager/libvaxis

- src/gwidth.zig
> gwidth: fix str.len comparison

- examples/main.zig
- examples/pathological.zig
- examples/table.zig
Hey. I was looking for a TUI framework for my small application in Zig. Wanted to see the examples, but some of them were broken. I fixed some of them, but not delved too much. Thought that my small contribution would help.
> Fix examples: main, pathological, table to build.

- src/Screen.zig
- src/Window.zig
Discovered/reproduceable by running flow in a very small terminal window.
> Fix a couple of segfaults when windows are partially or entirely off screen

- src/Screen.zig
I forgot to fix readCell too in the last PR.
> screen: fix off by one error in readCell bounds checks

- src/Window.zig
I'm told it's not unusual in the web world for multiple whitespace characters to be consumed as a single space. If that is the intention for `.word` wrap, that's fine with me! If not, this PR correctly prints all non-trailing whitespace.
I also chose to consume a `\r\n` sequence as intending a single newline, while all other sequences of `\r` and `\n` should produce multiple newlines.
> fix: `Window.printSegments` correctly prints all non-trailing whitespace

- src/Vaxis.zig
- src/ctlseqs.zig
And reset to default on cleanup.
> feat: add functions to set the default terminal background/foreground

- src/Cell.zig
- src/Window.zig
- src/widgets/TextInput.zig
- src/widgets/terminal/Terminal.zig
Cell is an often used structure, this should come with some decent
memory savings since there are cells stored twice (Screen and
InternalScreen).
> cell: change width type from usize to u8

- build.zig.zon
- src/Loop.zig
- src/Unicode.zig
- src/aio.zig
- src/widgets/terminal/Terminal.zig
- src/xev.zig
WidthData already includes grapheme_data. We were double allocating it!
> zg: remove grapheme_data init

- src/widgets/TextView.zig
> widgets.TextView: add intCast

- src/widgets/alignment.zig
For #95 
Note: Some of the position offsets are 0, so explicitly set them with `u16`.
> Add new alignment widgets

- src/Key.zig
Check if the target mods have shift or caps lock, and uppercase our
codepoint if they do. Someday we will need to allocate zg.case_data to
handle all of unicode casing, but for now we handle ascii until we
figure out a nice way to plumb in case_data.
> fix(matchText): uppercase target codepoint if shift or caps

- build.zig.zon
zg moved to: https://codeberg.org/atman/zg
I updated the dep to the latest tag
> deps: fix zg

- build.zig.zon
- src/Vaxis.zig
- add zero division check in the translateMouse function
- add kitty graphics check in every public function for transmitting image
> vaxis: checks 

- src/vxfw/App.zig
- src/vxfw/Button.zig
- src/vxfw/FlexColumn.zig
- src/vxfw/FlexRow.zig
- src/vxfw/RichText.zig
- src/vxfw/SizedBox.zig
- src/vxfw/Text.zig
- src/vxfw/vxfw.zig
- **vxfw: improve mouse handling and hit testing**
- **vxfw: use correct root window size**
> vxfw fix mouse and root window

- src/InternalScreen.zig
- src/Screen.zig
- src/Vaxis.zig
- src/Window.zig
- src/widgets/terminal/Screen.zig
> fix: integer overflow crash when screen w * h > max(u16)

- src/vxfw/ListView.zig
We set the value of pending_lines to -n, which has the side effect of
ignoring any subsequent scroll up events before the next draw. Subtract
the scroll up quantity from the current value, instead.
> vxfw(ListView): fix scroll up

- src/vxfw/RichText.zig
The trimmed_width calculation of softwrapped long words was incorrect.
Fix the calculation and add a test for the case.
> vxfw(RichText): fix softwrap of long words

- src/vxfw/App.zig
- src/vxfw/vxfw.zig
Add a command to copy text to the clipboard via OSC 52
> vxfw: add copy_to_clipboard command

- src/vxfw/App.zig
Change the core loop for handling of mouse events. We now do a layout
phase, which calls draw on the root widget. From here, we see  if the
widget underneath the mouse has changed and, if so, send mouse_enter and
mouse_exit events, then do another layout, and then *finally* we render.
This fixes a case where the mouse hasn't moved, but the content of the
screen has changed. The hover state of any widget will be updated in the
second layout phase if the app indicates a redraw is necessary from the
mouse_enter and mouse_exit events.
> vxfw: improve mouse handling

- build.zig.zon
Needed for fixing https://github.com/ghostty-org/ghostty/issues/6734
> switch zigimg ref to merged commit

- src/Parser.zig
IntelliJ IDEA's JediTerm terminal emulator sends the ancient xterm mouse button events `ESC [ M char(button + 32) char(x + 32) char(y + 32)`. This commit adds support for this.
Without this, when clicking inside jediterm, vaxis panics:
With this, it works fine:
> feat: support legacy xterm-style mouse events

- README.md
I'm new to zig, and want to play around with your TUI library. It took me a minute to figure out how to add it to my project. 
In the future when you have releases it will probably be a good idea to tie fetch to a ?tag=<tag name>.
the fetch command would become:
zig fetch --save git+https://github.com/rockorager/libvaxis?tag=<tag name>
> Add installation step

- src/vxfw/SizedBox.zig
> vxfw: fix SizedBox constraints

- src/vxfw/ListView.zig
> vxfw(ListView): use saturating subtraction in ListView.nextItem

- README.md
Updates README to show a method that works with ZLS (language server autocompletion)
> Update README: ZLS addition method shown

- src/tty.zig
> fix: initialize reader in PosixTty
