rockorager/libvaxis

- build.zig
- src/Tty-macos.zig
- src/select.zig
- src/vaxis.zig
the man page for macOS `poll(2)` says, under "bugs", that polling devices does not work, and indeed, although the current implementation based on poll(2) does produce output, it does not appear to actually be polling for this reason; instead the wait is blocking on the `read` call, causing the macOS user to need to input another character to exit.
this change introduces a wrapper over macOS's implementation of `select`, modeled after `std.io.poll` as `select.zig`. it is a compile error to use `select.zig` when `builtin.os.tag.isDarwin()` is false. a lightly altered version of `Tty.zig` accompanies this change. it's certainly possible to incorporate the two into one file; i didn't just to leave the other one in its original state.
with this change, writing to the pipe correctly exits. …
> fix: use `select` on macOS

- src/vaxis.zig
I don't know the extent to which you care about accuracy for rendering statistics. I found when working on seamstress that the `timestamp` calls in `std.time` were so unreliable as to be unusable, sometimes reporting negative time deltas within a single
function. `std.time.Timer`, on the other hand, has been rock-solid in my experience.
> fix: don't rely on `std.time.microTimestamp()` for accurate statistics

- build.zig
This reverts back to a `zig build example` step but sets up a flag to facilitate running all of them without the need to edit `build.zig` or add each as it's own step.
Example:
```sh
zig build example -Dexample=table
```
> build: add option for example to run

- src/Tty.zig
- src/main.zig
This allows [neurocyte/flow](https://github.com/neurocyte/flow) to use it's own event loop with libvaxis.
> vaxis: export Parser, Tty and getWinsize for applications that cannot use Loop

- examples/cli.zig
- examples/image.zig
- examples/main.zig
- examples/nvim.zig
- examples/pathological.zig
- examples/shell.zig
- examples/table.zig
- examples/text_input.zig
- src/Loop.zig
- src/Parser.zig
- src/Tty.zig
- src/Vaxis.zig
- src/ctlseqs.zig
- src/event.zig
I was not sure where to get an allocator for the pasted text, so I stole the grapheme allocator. Passing an allocator to parse is probably preferrable, but that felt like a large API change so I thought I'd let you decide.
> vaxis: add osc52 copy/paste support

- examples/pause_tui.zig
- examples/text_input.zig
- src/Mouse.zig
- src/Parser.zig
- src/Tty.zig
- src/Vaxis.zig
- src/ctlseqs.zig
- src/event.zig
This detects support for pixel mouse mode so it can be enabled only if supported.
This also translates pixel coordinates to something more compatible with plaine cell coordinates. This make it much easier to write applications that support both.
Also a commit for a crash on zero mouse reports.
> Add sgr-pixel detection and coordinate to offset translation

- src/Tty.zig
Attempting to close /dev/tty may block indefinitely on macos if another thread is already blocked on a read operation. As there is no practical use for closing /dev/tty on exit besides unblocking other threads (which does not work on macos anyway) we can just skip the close call.
> tty: do not close /dev/tty on macos

- src/Parser.zig
- src/Tty.zig
I forgot process the second parameter that determins if pixel mouse is actually supported or not.
> Fix pixel mouse detection

- src/xev.zig
libxev's .rearm semantics are unfortunately not very portable---rescheduling the exact same event on macOS / kqueue seems to cause the event loop to hang, while manually rescheduling and returning .disarm does not.
> fix: manually reschedule to avoid hang on macOS

- src/widgets.zig
- src/widgets/CodeView.zig
- src/widgets/LineNumbers.zig
- src/widgets/ScrollView.zig
- src/widgets/TextView.zig
Scrolling is a very common need in CLI applications. The ScrollView widget allows you to implement a scrollable content trivially. Provided is also a TextView for showing text content which is also a common task. It is not covered in this PR, but it would be nice if TextView could wrap the rendered text in future.
CodeView is something I had already laying around. It could be useful for showing more code like content and provide as a good starting point for writing your own editor widget.
> Introduce new standard widgets

- src/widgets/TextView.zig
If appending to a buffer through writer for example, the cols may not be correct if the writes don't end up in a newline (\n). Fix this by keeping track of the cols of previous append.
> TextView: fix cols when appending to a buffer

- src/widgets/ScrollView.zig
The ScrollView will panic if scroll.y is given a number that is outside the content size.
> ScrollView: do scroll bounds checking early

- .github/workflows/test.yml
- build.zig.zon
- src/Key.zig
- src/Parser.zig
this PR updates dependencies and `Key.zig` for compilation with zig 0.13.0. along the way i noticed that the test for `.cap_sgr_pixels` was failing, because the parsing logic was consuming the relevant character; the test now passes.
> fix: update to zig 0.13, broken test

- src/main.zig
Writing a custom Loop requires a few symbols that are not yet exported.
> build: export some symbols for thespian.Loop

- build.zig
`build.zig` file contains options to build the project.
One of these options is include_nvim, on line 5, as following:
```
[...]
const include_nvim = b.option(bool, "nvim", "Enable support for the neovim widget (default: false)") orelse true;
[...]
```
I've changed the default value (`orelse true`) to match the default description (`default: false`), resulting in the following:
```
[...]
const include_nvim = b.option(bool, "nvim", "Enable support for the neovim widget (default: false)") orelse false; 
[...]
```
Nice project BTW.
> Changed the default value of the nvim option to correspond to it's description

- examples/xev.zig
key events (and in fact all reads) on macOS via libxev require a thread pool. this PR adds a thread pool to the `xev` example.
> fix: add ThreadPool for key events on macOS

- src/Window.zig
this commit adds convenience to `Window.print` by allowing it to start printing at a nonzero column.
> feat: add col_offset to Window.print

- src/windows/Tty.zig
Both left and right coordinates are inside the screen area, so we have to add one.
> tty(windows): fix resize event screen size translation from srWindow

- src/xev.zig
This makes `xev.TtyWatcher` behave according to my expectations: namely that the callback will only fire after the function which registers it has returned.
> fix: don't call the callback synchronously on watcher init

- build.zig.zon
- examples/aio.zig
- src/Loop.zig
- src/aio.zig
- src/windows/Tty.zig
Update to latest aio, which has minor changes such as the thread pool argument and special aio.ReadTty operation.
In future the aio.ReadTty might have option to translate to vt escape sequences, but for vaxis it will use the direct mode.
I was not really able to test the windows at all actually as wine did not seem to play nice with any vaxis example, but it compiles and ... runs?
> aio: update to latest, windows, code reuse

- src/windows/Tty.zig
I'm not 100% certian that this is water tight. But I've tested it quite a bit and it seems to work fine.
> fix(windows): fix parsing of UTF-16 codepoints in eventFromRecord

- src/Vaxis.zig
on macOS, `@alignOf(std.c.max_align_t)` is 8, while `@alignOf(i128)` is 16. since we moved to using `std.time.Timer`, render duration should always be an unsigned quantity.
this change is motivated by my seamstress project, which wants to use a Vaxis struct (well, something with a Vaxis struct as a field) as a Lua userdata. it turns out that Lua won't allocate at an alignment greater than `@alignOf(std.c.max_align_t)` even if you ask it to.
> fix: use u64 for render_dur so that *Vaxis becomes align(8)

- build.zig.zon
- examples/aio.zig
- src/Loop.zig
- src/aio.zig
AFAIK zig lacks a way of overriding module dependencies of dependencies. LoopWithModules lets you use aio backend with vaxis using aio and coro modules that are not included by vaxis, when this function is used `include_aio` is not neccessary.
> aio: update aio, add LoopWithModules

- src/Loop.zig
Because the event is passed as a copy, the reference is `*const`, which caused the `mut_key.text = cache.put(text)` line to fail, since it was trying to modify the field of an immutable reference.
> Remove incorrect pointer capture

- examples/image.zig
The transmitted zig image is copied, instead of having its ownership transferred. So we need to add deinit to the image.
Closes #66
> fix memleak with transmitted image example

- src/Vaxis.zig
Attempt to reset the cursor shape on exit, if the shape has been
changed. This won't work on every terminal, however some implement
`\x1b[0 q` as setting the shape to the "default" value, others implement
it as a blinking block.
Fixes: #77
> vaxis: attempt to reset cursor shape

- src/Window.zig
I was seeing the following error:
> thread 29177 panic: integer overflow
> /home/Southporter/.cache/zig/p/1220fef553676a4c90035db27c13ad609d5823198a94cc971e95ab9c680e3dcd2df0/src/Window.zig:177:28: 0x10b5e42 in child (snail)
>         result.writeCell(w - 1, h -| 1, .{ .char = bottom_right, .style = style });
It looks like the height has saturating subtraction, but not the width offset.
I started running into this when I switched to the xev based loop, didn't really see it for the default vaxis loop.
> Adding saturating subtraction for width in Window.child

- examples/cli.zig
- examples/table.zig
- examples/vaxis.zig
- examples/view.zig
- src/Window.zig
- src/widgets/Table.zig
- src/widgets/View.zig
Print and PrintSegment are now infallible due to gwidth also being
infallible. The previous error was only error.OutOfMemory if a temporary
buffer was too small to encode text in gwidth. This has been removed in
favor or a for loop
> window: make print infallible

- src/Vaxis.zig
Move code to reset cursor and sgr state into `resetState` from `deinit`.
Fixes: #98
> core: reset cursor and sgr in resetState

- build.zig
- examples/fuzzy.zig
- examples/split_view.zig
- src/Screen.zig
- src/Window.zig
- src/main.zig
- src/vxfw/App.zig
- src/vxfw/Button.zig
- src/vxfw/Center.zig
- src/vxfw/FlexColumn.zig
- src/vxfw/FlexRow.zig
- src/vxfw/ListView.zig
- src/vxfw/Padding.zig
- src/vxfw/RichText.zig
- src/vxfw/SizedBox.zig
- src/vxfw/Spinner.zig
- src/vxfw/SplitView.zig
- src/vxfw/Text.zig
- src/vxfw/TextField.zig
- src/vxfw/vxfw.zig
Add an application framework which provides a standard widget interface, a set
of common widgets, and a high level application layer which manages all events.
The intent is to provide a high level framework that provides a more familiar
application development experience - similar to what one might see in Flutter, a
browser, GTK, etc.
The design is heavily influenced by Flutter, with a mix of Elm in there as well.
Notably this design uses far more mutation than in either, but this works to our
advantage in a language like Zig.
A widget must provide two functions: `handleEvent` and `draw`. Handle event
takes a context and an event. The context includes an `ArrayList(Command)` which
the widget may add commands to - such as "set the mouse shape to pointer", "give
this widget focus", …
> Add application framework

- src/vxfw/App.zig
- src/vxfw/vxfw.zig
Move capture handling of events to a different method on Widget. Having
capturing phase in the same method makes it very easy to accidentally
capture an event, producing confusing results. Browsers and GTK both
require handlers to explicitly listen to capturing phase events, so
there is precedence for having this as a separate method. For
applications that want to handle it all within the same function, the
signature is the same so they can use the same function for both methods
and achieve the same result.
> vxfw: add separate function pointer for event capturing

- src/vxfw/Button.zig
- src/vxfw/Center.zig
- src/vxfw/ListView.zig
- src/vxfw/Padding.zig
- src/vxfw/SizedBox.zig
- src/vxfw/SplitView.zig
- src/vxfw/TextField.zig
- src/vxfw/vxfw.zig
Don't require that surfaces explicitly declare mouse handling. We either
pass an event to the eventHandler or we don't. Along with this, we
remove all native widget passthrough events (IE we never pass an event
to a child). Native widgets which don't handle events also set
eventHandler to null, which prevents any null pointer issues also
> vxfw: remove handles_mouse from Surface

- src/Window.zig
When doing something like this
```zig
const win = vx.window();
const child = win.child(.{
.width = .{ .limit = 6 },
});
_ = try child.printSegment(
.{ .text = "Hello there how are you?" },
.{ .wrap = .word },
);
child.scroll(1);
```
The output is
```
there
how
are
you?
```
while it should be
```
there
how
are
you?
```
By using the screen width instead of the child one the scrolling gets fixed.
> fix Window scroll

- src/Vaxis.zig
- src/Window.zig
Accumulate any negative offsets in order to properly clip windows to
their parents. Previously, we only clipped if the window would be off
the screen from a negative offset. In the diagram below, we should
expect that if B is a child of A, it can't print in the non-overlapping
area. That is, B can only print in the overlapping region with A because
it is a child of A. This patch fixes this.
```
+-----------------------------------------------------+
|                                                     |
|              +--------+                             |
|              | B      |                             |
|              |    +---|-----+                       |
|              |    |   |     |                       |
|              +--------+     |                       |
| …
```
> window: fix negative offset clip

- src/vxfw/App.zig
- **vxfw: fix focus handler**
- **vxfw: don't clear ctx.cmds**
> vxfw fix focus

- src/main.zig
Move the recovery logic to a separate function so users of the library
may call it *without* using the default panic handler.
Reference: https://github.com/rockorager/libvaxis/discussions/146
> panic: move recovery log to separate function

- src/tty.zig
It should be pretty safe to assume that posix.empty_sigset is supported on most, if not all, posix systems. Individual OSes that need a different default value may add a case to the switch like macos.
This should open up support for most other posix systems.
closes #151
> tty: assume posix systems support posix.empty_sigset

- src/tty.zig
Some improvements to WindowsTty.  The init function will now catch and propagate an `error.InvalidHandle` so caller can catch/handle it.
In addition, I added packed structs for the input/output console modes which makes it convenient to manage the bits and is what zigwin32 generates for its bindings.  I also made these newly added types and wrapper functions public as they can be generally useful for terminal applications.
> WindowsTty: propagate ERROR_INVALID_HANDLE and provide packed structs

- USAGE.md
- src/main.zig
- src/widgets/LineNumbers.zig
- src/widgets/ScrollView.zig
- src/widgets/Scrollbar.zig
The loop namespace is used by the zig-aio loop for the handleEventGeneric function.
> Expose loop namespace, fix compile errors with some of the widgets

- build.zig
- examples/scroll.zig
- src/vxfw/ScrollBars.zig
- src/vxfw/ScrollView.zig
- src/vxfw/vxfw.zig
* Adds a `ScrollView` widget to `vxfw`.
* Adds a `ScrollBars` widget to `vxfw`.
* Adds a `scroll` example to demonstrate usage.
1. The view currently does not enforce a maximum width on the content to be able to correctly figure out whether the content can still be scrolled horizontally. This will cause the widget to draw beyond its boundaries horizontally.
2. When the last widget rendered is taller than a single row the whole widget will be drawn. This will cause the widget to draw beyond its boundaries vertically.
1. Run the `scroll` example with `zig build -Dexample=scroll example` and check that it behaves as expected.
2. To see the known issues in action you can add constraints to the draw context passed to the scroll bars and scroll view widgets in the `Model` and see how the views …
> Add scroll widgets

- README.md
- src/Loop.zig
- src/Vaxis.zig
- src/ctlseqs.zig
Implement explicit width hint extension, developed by kitty. When
both explicit width and mode 2027 are available, we default to explicit
width. Custom event loop authors will need to update their loops to add
support for this by setting the new capability value.
For simplicity, we don't actually add a flag in the parser for checking
between a cursor position and an F3 key. Instead, we send the cursor
home, then do an explicit width command, *then* check the cursor
position. If the cursor has moved - meaning the extension is supported -
we will see an F3 key with the shift modifier. The response will be
something like `\x1b[1;2R` which we parse as a shift+F3. But in the
loop, we check the flag if we have sent queries and handle this specific
event differently.
Reference: …
> caps!: implement explicit width extension

- src/Key.zig
Is there any reason why `tab`, `enter`, `escape`, `space` and `backspace` are not in `name_map`?
I use `name_map` [here](https://github.com/freref/fancy-cat/blob/feature/command-mode/src/config/Config.zig#L143) to convert user-inputted keys from a config file to their ASCII values. Would be nice if they were included.
> feature: add special keys to name map

- build.zig
the example list in build.zig was missing the split_view example, making it not buildable
> build: allow building split_view example

- examples/main.zig
- src/Cell.zig
- src/InternalScreen.zig
- src/Loop.zig
- src/Vaxis.zig
- src/ctlseqs.zig
Implement the kitty scaled text extension. We do this by adding a Scale
struct to the core Cell structure. The scale struct defines the scale,
numerator, denominator, and vertical positioning. We also query
independently for scaled text vs explicit width text.
Users of scaled text must be very careful of how they model their cells,
as cells must be written ahead of time with knowledge of the
capabilities of the underlying terminal. Libvaxis does not move contents
of cells based on scale (ie 3 contiguous cells of scale=2 with contents
"abc" will not transform into what you think - the user of the library
must take car to put a, b, and c into appropriate cells. Libvaxis will
do the work to prevent overwriting the cell). Capability can be checked
in the vx.caps.scaled_text value.
> feat: implement scaled text

- src/vxfw/vxfw.zig
Fix vxfw.Surface.satisfiesContraints to properly check constraints.
Note that I simply inverted the checks, I didn't change `>` to `>=`, so it may still be wrong. Let me know if you want a further edit. There are tests that assert a surface of width 10 fails to satisfy a max width of 10 constraint.
> vxfw: fix Surface.satisfiesConstraints

- README.md
- USAGE.md
Misuse of contractions.
See also:
- https://search.brave.com/search?q=it%27s+vs+its
- https://www.merriam-webster.com/grammar/when-to-use-its-vs-its
> fix typoes

- build.zig.zon
Use upstream. Instead of using the 0.14.1 release we are opting for this
commit since it includes the removal of `usingnamespace`, which means we
can have incremental compilation
> deps: update zigimg

- src/Loop.zig
- src/Parser.zig
- src/event.zig
This prevents reporting kitty mouse leave events as spurious mouse clicks.
> fix: add support for kitty mouse leave events

- README.md
- USAGE.md
- examples/cli.zig
- examples/image.zig
- examples/main.zig
- examples/table.zig
- examples/text_input.zig
- examples/vaxis.zig
- examples/view.zig
- examples/vt.zig
- src/Loop.zig
- src/Parser.zig
- src/Vaxis.zig
- src/ctlseqs.zig
- src/event.zig
- src/main.zig
- src/tty.zig
- src/vxfw/App.zig
- src/widgets/terminal/Command.zig
- src/widgets/terminal/Parser.zig
- src/widgets/terminal/Pty.zig
- src/widgets/terminal/Screen.zig
- src/widgets/terminal/Terminal.zig
- src/widgets/terminal/ansi.zig
- src/widgets/terminal/key.zig
This collection of commits gets the terminal example and the flow control editor working again with zig-0.15.
Additionally, there is a refactor to rename anyWriter() to just writer() and one to remove the unused reader in PosixTty.
As this is the fix list from Flow Control it is rebased onto the multi cursor support PR, so you might want to merge that first.
> fixes to get the Terminal widget and the Flow Control editor working with zig-0.15
